build:
  tags:
    - build
  image: node:latest
  stage: build
  script:
    - npm install --progress=false
    - npm install react-redux
    - npm install redux
    - npm install redux-devtools-extension
    - npm install redux-thunk
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

test:
  tags:
    - test
  image: node:latest
  stage: test
  script:
    - npm install --progress=false
    - echo "testing"

deploy:
    tags:
        - deploy
    image: node:latest
    stage: deploy
    script:
        - echo "Deployment"